### ISSUE TITLE
Add --clean option to the gem

### ISSUE THREAD

**Issue by dingo-d** [infinum/secrets_cli#26]
When reading the secret, the first line of the secret is usually something like

```bash
#<Vault::SecretAuth
```

And If I'm storing a JSON file in a vault, and in a CI/CD pipeline I'd like to do something like

```bash
secrets read -e staging | jq
```

So that I can parse it and use parts of it, I get 

> parse error: Invalid numeric literal at line 1, column 2

It would be good to have a new command line parameter `--clean` so that only the contents of the vault is shown (in my case a JSON file).

**Comment by d4be4st** [comment]
Removed the line completly in 1.12.3
