### ISSUE TITLE
When we use secrets_cli with AppRole instead of AppID

### ISSUE THREAD

**Issue by pmartens** [infinum/secrets_cli#4]
**When we use secrets_cli with AppRole instead of AppID?**
As of Vault 0.6.1, App ID is deprecated in favor of AppRole. AppRole can accommodate the same workflow as App ID while enabling much more secure and flexible management and other types of authentication workflows. No new features or enhancements are planned for App ID, and new users should use AppRole instead of App ID.

**Comment by pedroadame** [comment]
+1 Please update this to use AppRole.
